<?php

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require '../../../../vendor/autoload.php';

$mail = new PHPMailer(true);

if (isset($_POST['signup'])) {

    $user_id = $_POST['user_id'];
    $phone = $_POST['phone'];
    $qn = $_POST['qn'];
    $expert_id = $_POST['expert_id'];

    // date_default_timezone_set("Africa/Nairobi");
    // $current_time_stamp = date("Y-m-d H:m:d");

    // $report_date = $current_time_stamp;

    // For capitalization
    $qn = ucwords($qn);

    $queryqn = "SELECT * FROM users where id='$expert_id'";
    $resultqn = mysqli_query($conn, $queryqn);

    while ($retqn = mysqli_fetch_array($resultqn)) {
        $email = $retqn['email'];
        $first_nameq = $retqn['first_name'];
        $last_nameq = $retqn['last_name'];
        $expert_name = $first_nameq . " " . $last_nameq;
    }

    $querylz = "SELECT * FROM users where id='$user_id'";
    $resultlz = mysqli_query($conn, $querylz);

    while ($retlz = mysqli_fetch_array($resultlz)) {
        $first_namelz = $retlz['first_name'];
        $last_namelz = $retlz['last_name'];
    }

    if (str_word_count($qn) > 150) {
        echo "Maelezo Ni Mengi. Tafadhali Punguza";
    } else {

        $adduser = "INSERT INTO expertqn (user_id,phone,qn,expert_id) VALUES('$user_id','$phone','$qn','$expert_id');";

        $query = mysqli_query($conn, $adduser);

        if ($query) {

            try {
                // The SMTPDebug status zero (0) means debug informations won't show up. If two(2) then debugging informations shows up
                $mail->SMTPDebug = 0;
                $mail->isSMTP();
                $mail->Host     = 'smtp.titan.email;';
                $mail->SMTPAuth = true;
                $mail->Username = 'expert@pandadigital.co.tz';
                $mail->Password = '~ZWQN9,G;Kf9^}>';
                $mail->SMTPSecure = 'tls';
                $mail->Port     = 587;

                $mail->setFrom('expert@pandadigital.co.tz', 'Panda Digital');
                $mail->addAddress($email, $expert_name);
                // $mail->addAddress('jastonruggy@icloud.com');

                $mail->isHTML(true);
                $mail->Subject = 'Dear Expert ' . $expert_name;
                $mail->Body = 'Question Has Been Asked by ' . $first_namelz . " " . $last_namelz . '<br> ' . "<b>Question: </b>" . $qn . "<br> Please login to your Panda Digital Platform to answer the question <br><br><b>Don't Reply To This Email. It is autogenerated by Panda Digital Platform</b>";
                // $mail->AltBody = 'This Is A Good Practice';
                $mail->send();
            } catch (Exception $e) {
                echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
            }

            echo "Swali Lako Limetumwa Kikamilifu";
?>

            <!-- For Redirection -->
            <p id="time"></p>
            <script>
                function startTimer(duration, display) {
                    var timer = duration,
                        seconds;
                    setInterval(function() {
                        seconds = parseInt(timer % 60, 10);

                        seconds = seconds < 10 ? "0" + seconds : seconds;

                        display.textContent = "Inaelekeza ndani ya sekunde ... " + seconds + "Secs";

                        if (--timer < 0) {
                            timer = duration;
                            document.location.href = './<?php echo "?id=" . $id ?>';

                            function myFunction() {
                                location.replace("./<?php echo "?id=" . $id ?>")
                            }
                        }
                    }, 1000);
                }

                window.onload = function() {
                    var fiveMinutes = 1,
                        display = document.querySelector('#time');
                    startTimer(fiveMinutes, display);
                };
            </script>
<?php

        } else {
            echo "Imefeli";
        }
    }
}
?>
